name: Front-End request template
description: File a Front-End request. An appropriate label (Front-End) will be added. This label should already be present. If not create it manually so it will exist next time.
title: "[Product name]: "
labels: ["Front-End"]
assignees:
  - remcogerlich
body:
  - type: markdown
    attributes:
      value: |
        This report is designed for developers most fields are optional.
        Please make sure that someone can pickup this issue by assigning it.
  - type: dropdown
    id: Complexity
    attributes:
      label: Complexity
      description: How complex is this issue
      options:
        - easy
        - moderate
        - complex
    validations:
      required: true
  - type: dropdown
    id: Priority
    attributes:
      label: Priority
      description: What is the priority for a fix
      options:
        - low prio
        - medium prio
        - high prio
        - urgent (Immediately)
    validations:
      required: true
  - type: textarea
    id: what-needs-to-be-done
    attributes:
      label: What Needs to be Done?
      description: Please be as detailed as possible. We like images!?
      placeholder: Tell us what you you want!
      value: "I need a specific button to click and do awesome stuff"
    validations:
      required: false
